### ISSUE TITLE
Option to add space in DisplayName when Test Method is written with Underscore

### ISSUE THREAD

**Issue by noufionline** [joaroyen/ReSharper.LiveTemplates#2]
Hi Joaroyen,

Really appreciate your contribution!

Can you please provide another functionality which could give results as follows
`[Fact(DisplayName="My Test Method Should Return False")]
public void My_Test_Method_Should_Return_False()
{

}
`

The typing will be done in Display Name text and the corresponding method should adjust with proper underscores.

Thanks in advance.

**Comment by noufionline** [comment]
Found a work around. Thansk

**Comment by joaroyen** [comment]
Cool :)

Thanks for your interest in this simple addition to ReSharper.
