### ISSUE TITLE
2016.3 support?

### ISSUE THREAD

**Issue by chrisstaley** [joaroyen/ReSharper.LiveTemplates#3]
I rely heavily on your ValidIdentifierMacro when writing unit tests, but I noticed that this extension is not available for R# 2016.3.  Is that something on Jetbrains' side, or is there a modification that needs to be made to the extension?  I'd be glad to help anyway I can.

**Comment by joaroyen** [comment]
I need to update the extension to use the latest SDK and upload the new version that is compatible with the current wave of ReSharper platfomr to JetBrains.

This is usually a pretty straight forward operation, but it is something I have postponed during the eap program. 2016.3 was released today, and if I don't get around to update the macros today or tomorrow, I will definitely do it this weekend. 

I would gladly accept a pull request if you want to try to update the extension yourself. You can look at the 2016.2 commit (basically update NuGet packages and bump the supported Wave version), but as I said, I will get around to do this during the weekend (I need it myself to start using VS2017). If you want to send me a pull request, give me a heads up.

**Comment by joaroyen** [comment]
New version supporting ReSharper 2016.3 is now available in the ReSharper Gallery. Keep in mind that I've just done the bare minimum of testing.

**Comment by chrisstaley** [comment]
Fantastic!  I was literally just sitting down to take a crack at it myself.

Thanks for the quick turnaround.


chris
