### ISSUE TITLE
How do I use this plugin?

### ISSUE THREAD

**Issue by vdurante** [joaroyen/ReSharper.LiveTemplates#4]
I have installed the plugin, but apparently I can't find a way to use it! Can you help me out?

**Comment by joaroyen** [comment]
These macros are used when you author live templates in ReSharper. They are listed among the built in macros in the Template Editor when selecting to use a macro for a template parameter: https://www.jetbrains.com/help/resharper/Reference__Template_Editor.html.

I've included a very simple test method template in the templates.dotSettings as an example, and you can import it from the Template Explorer window: https://www.jetbrains.com/help/resharper/Templates__Managing_Templates__Importing_and_Exporting_Templates.html. (ps: I haven't tested this import in a long time, but I assume JetBrains haven't changed the format).
